export const listOfPets = [
    {
        'id': '1',
        'type': 'dogs',
        'name': 'Chó Corgi',
        'img': 'https://cdnn1.img.vn.sputniknews.com/img/07e6/03/15/14329528_252:0:1689:1078_1920x0_80_0_0_67a8626837bba47c567b6c51e3e73dd9.jpg',
        'petsReview': '',
        'price': '1000$ - 2500$',
        'origin': ' xứ Wales (vương quốc Anh)',
        'description': "Có 2 giống Corgi xứ Wales là Cardigan & Pembroke, tên gọi giống theo địa danh chúng xuất hiện. Sự khác biệt nổi bật là cấu trúc xương, chiều dài cơ thể. Corgi Cardigan có kích thước lớn hơn so với Pembroke. Cardigan có màu sắc đa dạng hơn, nhưng màu trắng không được chiếm ưu thế. Cardgan Corgi mạnh mẽ, năng động, thông mình & khá điềm tĩnh. Trong khi đó Corgi Pembroke thấp lùn, thông minh, nhanh nhẹn với khả năng làm việc  cường độ cao ở các trang trại. Pembroke có đôi tai nhọn, phần đầu giống cáo với đuôi ngắn (hoặc được cắt từ nhỏ). Nếu không cắt, đuôi Pembroke thường xoăn cuộn, trong khi đuôi Cardigan thẳng hàng với cơ thể, to, dài (khoảng 30 cm) và không được cắt.",
    },

    {
        'id': '2',
        'type': 'dogs',
        'name': 'Chó Phốc Sóc (Pomeranian)',
        'img': 'https://images.unsplash.com/photo-1626211596179-d1fe8beaf75c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8cG9tZXJhbmlhbnxlbnwwfHwwfHw%3D&w=1000&q=80',
        'petsReview': '',
        'price': '1000$ - 2500$',
        'origin': 'vùng Pomerania (nước Đức)',
        'description': "Pomeranian được Hiệp hội chó giống quốc tế FCI (Fédération Cynologique Internationale) xác định là một phần của giống German Spitz (chó Spitz Đức). Giống chó này có 5 size, trong đó Pomeranian có kích thước nhỏ nhất, (được gọi là Dwarf Spitz). Pom cũng là giống nhỏ nhất trong nhóm Spitz (chó kéo xe, chó tuyết) so với chó Alaska, Samoyed, Husky, Chow chow, Akita Inu... Tên gọi Pomeranian xuất phát từ quê hương của giống chó này, tỉnh Pomerania, nước Đức. Chúng trở nên phổ biến khi nữ hoàng Victoria yêu thích và phát triển trên lãnh thổ Vương quốc Anh rộng lớn.",
    }, {
        'id': '3',
        'type': 'dogs',
        'name': 'Chó Husky Sibir',
        'img': 'https://images.unsplash.com/photo-1605568427561-40dd23c2acea?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fGh1c2t5fGVufDB8fDB8fA%3D%3D&w=1000&q=80',
        'petsReview': '',
        'price': '1500$ - 3000$',
        'origin': 'Siberia (liên bang Nga)',
        'description': "Có 2 giống Corgi xứ WaleChó Husky là giống chó lao động mạnh mẽ chuyên vận chuyển hàng hóa với tốc độ cao, khác với chó Alaska chuyên chở hàng nặng trên tuyết. Là thành viên của nhóm chó tuyết Spitz (bao gồm: Alaska, Samoyed, Husky, Chow chow, Akita Inu...) Tộc người Chukchi ở vùng Siberian nước Nga đã dùng Husky trong hàng trăm năm để kéo xe trượt tuyết, chăn các đàn tuần lộc và cảnh giới.s là Cardigan & Pembroke, tên gọi giống theo địa danh chúng xuất hiện. Sự khác biệt nổi bật là cấu trúc xương, chiều dài cơ thể. Corgi Cardigan có kích thước lớn hơn so với Pembroke. Cardigan có màu sắc đa dạng hơn, nhưng màu trắng không được chiếm ưu thế.",
    }, {
        'id': '4',
        'type': 'cats',
        'name': 'Mèo Anh lông ngắn (Aln) - British Shorthair',
        'img': 'https://dogily.vn/wp-content/uploads/2022/08/meo-anh-long-ngan-british-shorthair.jpg',
        'petsReview': '',
        'price': '500$ - 2000$',
        'origin': 'Vương Quốc Anh',
        'description': "British Shorthair là giống mèo cảnh cổ của Vương quốc Anh. Chúng đã có quá trình sinh sống và phát triển trên quần đảo Anh quốc từ hàng ngàn năm. Từng có nguy cơ bị tuyệt chủng sau hai cuộc chiến tranh thế giới thứ I và II. Nhưng nhờ những nỗ lực phục hồi, ngày nay giống mèo này trở thành một trong các dòng thú kiểng được ưa thích và phổ biến nhất.",
    }, {
        'id': '5',
        'type': 'cats',
        'name': 'Mèo Anh lông dài - Mèo Ald British Longhair',
        'img': 'https://dogily.vn/wp-content/uploads/2022/08/meo-anh-long-dai.jpg',
        'petsReview': '',
        'price': '500$ - 2000$',
        'origin': 'Vương Quốc Anh',
        'description': "British Longthair là giống mèo cảnh cổ của Vương quốc Anh. Chúng đã có quá trình sinh sống và phát triển trên quần đảo Anh quốc từ hàng ngàn năm. Từng có nguy cơ bị tuyệt chủng sau hai cuộc chiến tranh thế giới thứ I và II. Nhưng nhờ những nỗ lực phục hồi, ngày nay giống mèo này trở thành một trong các dòng thú kiểng được ưa thích và phổ biến nhất.",
    }, {
        'id': '6',
        'type': 'cats',
        'name': 'Mèo Ba Tư',
        'img': 'https://toigingiuvedep.vn/wp-content/uploads/2021/04/hinh-anh-meo-ba-tu-long-vang-nau-de-thuong.jpg',
        'petsReview': '',
        'price': '500$ - 2000$',
        'origin': 'Iran',
        'description': "Mèo Ba Tư (còn gọi là mèo Persian) là giống mèo có nguồn gốc từ thời Ba Tư cổ đại (Iran ngày nay). Chúng được xem như giống mèo bản địa ở Iran hiện nay. Được người Anh mang về nhân giống, giờ đây chúng phát triển rất mạnh mẽ ở các nước Châu Âu.",
    }, {
        'id': '7',
        'type': 'cats',
        'name': 'Mèo Sphynx',
        'img': 'https://upload.wikimedia.org/wikipedia/commons/1/1e/Cat_-_Sphynx._img_004.jpg',
        'petsReview': '',
        'price': '1000$ - 2500$',
        'origin': 'Toronto - Canada',
        'description': "Mèo Sphynx là giống mèo bị đột biến gen tự nhiên không qua cấy ghép. Chú mèo Sphynx đầu tiên xuất hiện vào năm 1966 ở Toronto, Canada. Chú là kết quả của cuộc giao phối của 2 con mèo khác.",
    },
    {
        'id': '8',
        'type': 'dogs',
        'name': 'Chó Poodle',
        'img': 'https://poodlefamily.com/wp-content/uploads/2020/11/toy-poodle.png',
        'petsReview': '',
        'price': '400$ - 1500$',
        'origin': 'Pháp và Đức',
        'description': "Chó săn vịt là một giống chó săn dùng để săn các loại thủy cầm trong đó chủ yếu là vịt. Ngày nay giống chó này được lai tạo để trở thành dòng chó cảnh. Tên 'Poodle' của chúng xuất phát từ chữ 'Pudel' trong tiếng Đức, nghĩa là 'thợ lặn' hay là 'chó lội nước' và bộ lông của chúng có thể đè bẹp cơ thể khi ở trong nước.",
    },
    {
        'id': '9',
        'type': 'cats',
        'name': 'Mèo Ragdoll',
        'img': 'https://petmaster.vn/petroom/wp-content/uploads/2020/04/meo-ragdoll-5.jpg',
        'petsReview': '',
        'price': '500$ - 1000$',
        'origin': 'Riverside - US',
        'description': "Ragdoll là một giống mèo với đôi mắt màu xanh dương và bộ lông hai màu tương phản đặc trưng. Nó là giống mèo to lớn, với cơ bắp rắn chắc và bộ lông mềm mại và hơi dài Chúng cũng được biết đến là giống mèo hiền lành và dễ bảo.",
    },
    {
        'id': '10',
        'type': 'dogs',
        'name': 'Chó Alaska',
        'img': 'https://thucanh.net/wp-content/webpc-passthru.php?src=https://thucanh.net/wp-content/uploads/2021/02/anh-cho-alaska122.jpg&nocache=1',
        'petsReview': '',
        'price': '1000$ - 5000$',
        'origin': 'Alaska',
        'description': "Chó Alaska có tên gọi đầy đủ là chó Alaska Malamute có nguồn gốc từ giống chó sói tuyết hoang được thuần hóa và trở thành một thú nuôi phổ biến. Giống chó này được biết được thuần hóa và huấn luyện người dân Alaska và dần phổ biến ở Mỹ.",
    },
    {
        'id': '11',
        'type': 'cats',
        'name': 'Mèo Munchkin',
        'img': 'https://azpet.b-cdn.net/wp-content/uploads/2022/06/M748-M12463-1.jpg',
        'petsReview': '',
        'price': '500$ - 1500$',
        'origin': 'US',
        'description': "Mèo Munchkin là một giống mèo nhà có nguồn gốc từ Hoa Kỳ. Chúng được đặc trưng bởi tứ chi ngắn ngủn.",
    },
    {
        'id': '12',
        'type': 'dogs',
        'name': 'Chó Phú Quốc',
        'img': 'https://bachkhoaland.com/wp-content/uploads/2021/06/khuon-mat-cho-phu-quoc-819x1024.jpg',
        'petsReview': '',
        'price': '300$ - 1000$',
        'origin': 'Phú Quốc - Việt Nam',
        'description': "Chó Phú Quốc là một loại chó riêng của đảo Phú Quốc, Việt Nam. Nó có đặc điểm phân biệt với các loại chó khác là các xoáy lông ở trên sống lưng. Nó là một trong ba dòng chó có xoáy lông trên lưng trên thế giới. Hai loại chó lông xoáy ở lưng còn lại là chó lông xoáy Rhodesia và chó lông xoáy Thái.",
    },
]